#########################################
# .cshrc file for mdtest
#########################################

if ( $?prompt ) then
  set prompt = "`hostname`:\!>"
  set autoexpand
  set autolist
  set cdpath = ( ~ )
  set pushdtohome
endif

unset autologout
set autologout=0

umask 002
setenv TAPE /dev/st0
setenv PRINTER eol-nwcolor

#unsetenv MANPATH

setenv EDITOR emacs
setenv PAGER less
setenv LESS "-cMe"
setenv LESSOPEN "|lesspipe.sh %s"
setenv LESSCHARSET latin1

# hostname

set hostname=`hostname`

# git completion

if ( -f $HOME/.git-completion.csh ) then
    source $HOME/.git-completion.csh
endif

# HOST_OS

setenv HOST_OS LINUX_NCXX
setenv PKG_CONFIG_PATH /usr/lib64/pkgconfig

# Set the build environment

setenv LANG C
setenv LROSE_INSTALL_DIR $HOME/lrose
setenv LROSE_CORE_DIR $HOME/git/lrose-core
setenv CODEBASE $HOME/git/lrose-core/codebase

setenv RAP_LIB_DIR $LROSE_INSTALL_DIR/lib
setenv RAP_BIN_DIR $LROSE_INSTALL_DIR/bin

setenv RAP_MAKE_INC_DIR $CODEBASE/make_include
setenv RAP_MAKE_BIN_DIR $CODEBASE/make_bin

setenv RAP_INC_DIR $LROSE_INSTALL_DIR/include
setenv RAP_MAN_DIR $LROSE_INSTALL_DIR/man
setenv RAP_DOC_DIR $LROSE_INSTALL_DIR/doc

setenv RAP_SHARED_INC_DIR $RAP_INC_DIR
setenv RAP_SHARED_LIB_DIR $RAP_LIB_DIR
setenv RAP_SHARED_BIN_DIR $RAP_BIN_DIR
setenv RAP_SHARED_MAN_DIR $RAP_MAN_DIR
setenv RAP_SHARED_DOC_DIR $RAP_DOC_DIR

setenv RVP8_INC_DIR $LROSE_INSTALL_DIR/include

setenv MY_NETCDF4_INCS
setenv MY_NETCDF4_LIBS

setenv MY_CFLAGS
setenv MY_CPPC_CFLAGS " -std=c++11 "

setenv GCC_WARNINGS "-Wall"

setenv READYFLOW_7142_428_LINUX $HOME/svn/spoldrx/trunk/src/ReadyFlow/1.0
setenv WINDRIVERVERSION 1150

# --- OTHER BUILD SETTINGS

setenv QTDIR /usr/local/qt4
setenv FC gfortran

# --- LD library path --

setenv LD_LIBRARY_PATH $RAP_LIB_DIR

# --- NCAR GRAPHICS ---

setenv NCARG_ROOT /usr/local/ncarg

# --- JAVA ---

setenv JAVA_HOME /usr/java/latest
setenv ANT_HOME /usr/local/ant
setenv RAP_INST_JAVA_DIR $RAP_LIB_DIR

# --- RELEASES ---

setenv RELEASES $HOME/releases

# --- RUNTIME ---

setenv PROJ_DIR $HOME/projDir
setenv DATA_HOST localhost
setenv TITAN_HOME $PROJ_DIR
setenv DATA_DIR $PROJ_DIR/data
setenv RAP_DATA_DIR $DATA_DIR
setenv RADX_DATA_DIR $DATA_DIR/radx
setenv TMP_DIR $DATA_DIR/tmp
setenv LOG_DIR $PROJ_DIR/logs
setenv DATA_DISTRIB_LOG_DIR $LOG_DIR/distrib
setenv ERRORS_LOG_DIR $LOG_DIR/status
setenv RESTART_LOG_DIR $LOG_DIR/restart

setenv PROCMAP_HOST localhost
setenv DATA_MAPPER_ACTIVE true
setenv LDATA_FMQ_ACTIVE true

setenv DS_COMM_TIMEOUT_MSECS 60000
setenv DS_PING_TIMEOUT_MSECS 20000

# udunits XML

#setenv UDUNITS2_XML_PATH /usr/share/udunits/udunits2.xml
#setenv UDUNITS2_XML_PATH /opt/local/lib/udunits2.xml

# --- project info --- 

if (-f $PROJ_DIR/system/params/project_info) then
  source $PROJ_DIR/system/params/project_info
endif

# --- PYTHON ---

#setenv PYTHONPATH /usr/lib/python2.?/site-packages
setenv PYTHONPATH ~/anaconda2/pkgs

# -------- HSRL --------

setenv HSRL_CONFIG ~/hsrl_config
setenv GRIB_CACHE /scr/eldora1/HSRL_data/GFS_cache

# --- Path ---

# Assemble path to include all scripts directories
# then projDir/bin, then the rest

set path = (.)
set path = ($path ~/bin)

if ( -d $LROSE_INSTALL_DIR/bin ) then
  set path = ($path $LROSE_INSTALL_DIR/bin)
endif

if ( -d $PROJ_DIR ) then
  foreach dir ($PROJ_DIR/*)
    if (-d $dir/scripts) then
      set path = ($path $dir/scripts)
    endif
  end
endif

set path = ($path ~/cidd/bin)
set path = ($path /usr/lib64/qt4/bin)
set path = ($path ~/anaconda2/bin)
set path = ($path $JAVA_HOME/bin $ANT_HOME/bin)
set path = ($path /usr/bin)
set path = ($path ~/bin)
set path = ($path /opt/local/bin)

set path = ($path \
	$NCARG_ROOT/bin \
        /usr/X11R6/bin /sbin /usr/sbin /usr/bin /sbin /bin \
	/usr/bin/X11 /usr/local/bin /usr/local/sbin \
	/opt/gfortran/irun/bin \
        /usr/lib64/qt4/bin /usr/lib/qt4/bin )

set path = ($path /home/mdtest/src/HDFView/2.11.0/bin )

# -- core files --
# unlimit coredumpsize

# --- Aliases ---
if ($?prompt) then

  alias sc source ~/.cshrc

  alias setprompt 'set prompt="(`hostname`) `basename $cwd` ! % "'
  alias cd 'cd \!*;setprompt; echo $cwd'
  alias push 'pushd \!*; cd .'
  alias pop 'popd; cd .'

  set prompt = "%m:%~%# "             # tcsh
  set showdots                        # tcsh
  set watch = (1 root any)            # tcsh
  set history=100
  alias h history
  # set savehist=0
  set nobeep
  set time = 5

  alias ssh 'ssh -XY'

  alias rm 'rm -i'
  alias mv 'mv -i'
  alias cp 'cp -i' 

  alias df 'df -h'
  set filec
  set fignore = (.o .ln)

  alias catw 'cat `which \!*`'
  alias lessw 'less `which \!*`'
  alias emacsw 'emacs -nw `which \!*`'
  alias viw 'vi `which \!*`'

  alias lst 'ls -l \!* | awk \{s+=\$4\}END\{print\ s\}'
  alias la 'ls -la --color=tty'
  alias ll 'ls -l --color=tty'
  alias lt 'ls -lt --color=tty'
  alias lat 'ls -alt --color=tty'
  alias l 'ls -sF'
  alias L ls -agl
  alias LS ls -aFRts 

  alias clone-cfradial 'git clone https://github.com/NCAR/CfRadial'
  alias clone-lrose-core 'git clone https://github.com/NCAR/lrose-core'
  alias clone-lrose-netcdf 'git clone https://github.com/NCAR/lrose-netcdf'

  alias gstat 'git status'
  alias gcom 'git commit -am \!*'
  alias gpush 'git push'
  alias gpull 'git pull'
  alias gdiff 'git diff '
  alias gdt 'git difftool -g -y '

  alias xx 'xrdb -override ~/.Xdefaults'
  alias cvs 'cvs -d :pserver:dixon@cvs.rap.ucar.edu:/cvs \!*'
  alias cvsforward 'ssh -a -x -C -Y -R 2401:localhost:2401'
  alias cvsin 'ssh -a -x -C -L 2401:cvs.rap.ucar.edu:2401'
  alias cvsout 'ssh -a -x -C -R 2401:cvs.rap.ucar.edu:2401'
  alias cvsclosed 'cvs -d :pserver:dixon@cvs:/cvs_closed \!*'

  alias psg 'ps axww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias pslg 'ps alxww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias psug 'ps auxww | sed -n "1p; \|sed .*/\!*/|d; /\!*/p"'
  alias psx 'ps xww | grep -v LogFilter'
  alias ensc 'enscript -2r -fCourier7'

  alias looka 'grep \!* /usr/lib/aliases'
  alias lookg 'grep \!* /etc/group'
  alias lookp 'grep \!* /etc/passwd'
  alias lookh 'grep \!* /etc/hosts'

  alias print_procmap 'print_procmap -hb -up -status'
  alias PrintDataMap 'PrintDataMap -all -relt -lreg'
  alias ppm 'print_procmap -hb -up -status'
  alias pdm 'PrintDataMap -all -relt -lreg'
  alias pcheck 'procmap_list_check -proc_list $PROJ_DIR/control/proc_list'
  alias ph 'get_host_type'

  alias hsrl 'ssh -a -X -Y -C -R 8083:archiver:8083 -L 9001:archiver:9001 hsrl'
  alias gate 'ssh -a -x -C -L 2401:cvs.rap.ucar.edu:2401 dixon@gateway'
  alias front 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 -p 22 dixon@front.eol.ucar.edu'
  alias eldora 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 dixon@eldora.eol.ucar.edu'
  alias hail 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 dixon@hail.eol.ucar.edu'
  alias rain 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 dixon@rain.eol.ucar.edu'
  alias reldora 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 rsfdata@eldora.eol.ucar.edu'
  alias rhail 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 rsfdata@hail.eol.ucar.edu'
  alias rrain 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 rsfdata@rain.eol.ucar.edu'
  alias titan 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 dixon@titan.eol.ucar.edu'
  alias mdtest 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 mdtest@titan.eol.ucar.edu'

  alias tikal 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 dixon@tikal.eol.ucar.edu'
  alias barolo 'ssh -a -X -Y -C -R 2401:cvs.rap.ucar.edu:2401 dixon@barolo.eol.ucar.edu'

  alias cvsforward22 'ssh -p 22 -a -x -C -R 2401:localhost:2401'

# save to dvd

  alias savedvd 'growisofs -Z /dev/dvd -r -J'
  alias saveiso2dvd 'growisofs -dvd-compat -Z /dev/dvd='

  if (-f ~/.dircolors) then
    eval `dircolors ~/.dircolors`      # Set up color-ls variables.
  endif

endif

