#! /bin/csh

# rsync the data across to HCR
#
# in the lab we transfer to eldora as well

cd $DATA_DIR

echo "================= rsync hsrl data to hcr ================"
set hcr = hcr-router.eol.ucar.edu
set dest = projDir/data/hsrl
ssh hcr@${hcr} mkdir -p ${dest}
rsync -av raw cfradial monitoring spdb hcr@${hcr}:${dest}
echo "===================== done =============================="

echo "=============== rsync hsrl data to eldora ============="
set eldora = eldora.eol.ucar.edu
set dest = /scr/eldora1/rsfdata/hsrl
ssh rsfdata@${eldora} mkdir -p ${dest}
rsync -av raw cfradial monitoring spdb rsfdata@${eldora}:${dest}
echo "======================= done =============================="

