#! /bin/csh

# rsync the data across to USB stick
# Make sure you mount the USB stick first
#
#  cd ~/projDir/system/scripts
#  sudo ./mount_usb

cd ~hsrl/projDir/data

echo "================= rsync hsrl data to usb ================"

mkdir /data/usb/archive
rsync -av --size-only raw cfradial monitoring spdb logs images /data/usb/archive |& grep -v mkstemp

